### ISSUE TITLE
[Site] Expired certificate on modpagespeed.com

### ISSUE THREAD

**Issue by leecalcote** [crowell/modpagespeed#2081]
The certificate used on modpagespeed.com expired on August 11th, 2021.

<img width="526" alt="Screen Shot 2021-09-15 at 1 11 48 PM" src="https://user-images.githubusercontent.com/7570704/133487413-491863bf-6115-4e89-9e14-67ee69b8e68e.png">

If this is a duplicate issue, please close at-will.

**Comment by oschaaf** [comment]
Thanks for reporting. I don’t observe that warning .. and https://www.ssllabs.com/ssltest/analyze.html?d=www.modpagespeed.com&latest seems to check in OK. It’s suspect you do get that warning though .. I can only assess from my phone atm but tomorrow I can dive in deeper

**Comment by oschaaf** [comment]
Ah I see, confirmed via https://www.ssllabs.com/ssltest/analyze.html?d=modpagespeed.com&latest

**Comment by oschaaf** [comment]
Resolved
