### ISSUE TITLE
Failure running 'wget https://github.com/apache/incubator-pagespeed-ngx/archive/latest.zip

### ISSUE THREAD

**Issue by palermomarco** [crowell/modpagespeed#2086]
It looks like the zip file is not available anymore at https://github.com/apache/incubator-pagespeed-ngx/archive/latest.zip

The automated install explained here https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source won't work anymore.

Could anyone please help?

**Comment by Lofesa** [comment]
Hi
You can try https://github.com/apache/incubator-pagespeed-ngx/archive/latest-stable.zip or latest-beta.zip

**Comment by palermomarco** [comment]
sounds perfect, thanks!
