### ISSUE TITLE
Failed to install nginx pagespeed module due SSL expired Certificate

### ISSUE THREAD

**Issue by pablo-silveira** [crowell/modpagespeed#2090]
I noticed that the certificate SSL of  https://ngxpagespeed.com expired on April 13th.
So I receiving an error when executing `bash <(curl -k -f -L -sS https://ngxpagespeed.com/install)` .

Do you have any estimated to renewal this certificate or some workaround to solve this issue?

Thanks!

**Comment by oschaaf** [comment]
Should be fixed!
