### ISSUE TITLE
Admin page 500 error

### ISSUE THREAD

**Issue by ghost** [crowell/modpagespeed#2106]
I get a 500 Internal Server Error when accessing the admin page.
apache error log
`[core:error] [pid 1396836:tid 1396999] [client 60.105.163.120:0] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.`
Is it possible to hide the PageSpeed version?

**Comment by Lofesa** [comment]
Maybe there us a musconfiguration in the apache server.
To set admin pages:
https://www.modpagespeed.com/doc/admin

To set the X-Mod-Pagespeed

ModPagespeedXHeaderValue "Powered By mod_pagespeed"
